Access_token:  #it will be auto picked
Account_ID: FA79300 
Secret_Code: 7fk3KRGdck3qIbnn6LIjnqJEepjGZabNGY7gdKNgKdCa4ZONBGIkZnn1Xg6dalDj #  
UID: FA79300 
client_id: FA79300  
oauth_url: https://api.shoonya.com/NorenWeb/authorize/oauth
