name: Run Trading Bot

on:
  schedule:
    - cron: '15 3 * * 1-5' # 9:15 AM IST (Monday-Friday)
  workflow_dispatch:      # Allows manual runs

permissions:
  contents: write         # Allows the bot to push the CSV file back

jobs:
  trade_execution:
    runs-on: ubuntu-latest
    env:
      # This tells GitHub to use the newer Node engine immediately
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests NorenRestApiPy pyotp pandas scipy numpy websocket-client

      - name: Run Trading Bot
        env:
          env:
          TOKEN: ${{ secrets.SHOONYA_TOTP_SECRET }} # Ensure this matches your secret name
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python -u BSM_WithAdjoints.py
          python -u MA0921.py
          python -u bot.py
